version: "3.8"

services:
  oracle:
    image: truevoly/oracle-12c
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
      - 8050:8080
    volumes:
      - db:/u01/app/oracle
  app:
    depends_on:
      - oracle
    build: ./server
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
